### ISSUE TITLE
[multipoly] / [s2p.m] Convert the [symbolic] value to [polynomial] value 

### ISSUE THREAD

**Issue by Wogwan** [SOSAnalysis/multipoly#1]
Hi,
Great appreciate for your work! 
Here just a small question for convert function from **syms form** to **pvar form**? 

From multipoly/doc, it hints that command s2p.m is available. But when I used it, an error occurred for missing [findsym.m]  function.

At your convenience, would you please have an update reply for it? Thanks!

[MATLAB R2021A]
[system: Win64]

**Comment by tcunis** [comment]
Hello Wogwan,

It looks to me like this function has been written using the method `findsym` from Matlab’s symbolic math toolbox, which is no longer available in newer versions of SMT. 

Could you try replacing it by [`symvar`](https://www.mathworks.com/help/symbolic/symvar.html)?

Best,
Torbjørn

**Comment by Wogwan** [comment]
function p=s2p(s)
% function p=s2p(s)
%
% DESCRIPTION
%   Converts from a symbolic toolbox polynomial to a multipoly polynomial.
%
% INPUTS
%   s: Polynomial created using the symbolic toolbox
%
% OUTPUTS
%   p: Polynomial created using the multipoly toolbox
%
% SYNTAX
%   p = s2p(s)
%
% See also p2s

% 1/30/2003: PJS  Initial Coding
% 11/23/2010 PJS  Updated for matrix polynomials and to use sym/eval

if ~isa(s,'sym')
    error('Input must be a symbolic toolbox object');
end

% Convert to variable precision arithmetic
s = vpa(s);

% Create pvars for each variable in s
% vars = findsym(s); % Original Version
vars = strip(char(symvar(s)),'left','[');
vars = strip(vars,'right',']');
vars = erase(vars,' ');

% Original Version
% if isempty(vars)
%     nv = 0;
% else
%     vidx = [0 strfind(vars,',') length(vars)+1];
%     nv = length(vidx)-1;
% end
% for i1 =1:nv
%     varname = vars(vidx(i1)+1 : vidx(i1+1)-1);
%     pvar(varname);
% end

if isempty(vars)
    nv = 0;
else
    vidx = [0 strfind(char(vars),',') length(char(vars))+1];
    nv = length(vidx)-1;
end
for i1 =1:nv
    varname = vars(vidx(i1)+1 : vidx(i1+1)-1);
    pvar(varname);
end

% Expand the polynomial 
se = expand(s);

% Evaluate in symbolic expression to convert to multipoly
p = eval(se);
